version: "3.8"

services:
  gobin:
    image: ghcr.io/topi314/gobin:master
    container_name: gobin
    restart: unless-stopped
    volumes:
      - ./gobin.toml:/var/lib/gobin/gobin.toml
      - ./gobin.db:/var/lib/gobin/gobin.db
    ports:
      - 80:80
