name: CLI

on:
  push:

jobs:
  cli-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, 386, arm, arm64]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm
          - goos: windows
            goarch: arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true

      - name: File Extension Windows
        if: ${{ matrix.goos == 'windows' }}
        run: echo "file_extension=.exe" >> $GITHUB_ENV

      - name: Create Dist Folder
        run: mkdir dist

      - name: Prepare Version Info
        run: |
          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date --rfc-3339=seconds)" >> $GITHUB_ENV

      - name: Build
        run: |
          CGO_ENABLED=0
          GOOS=${{ matrix.goos }}
          GOARCH=${{ matrix.goarch }}
          go build -ldflags="-X 'main.Version=${{ env.VERSION }}' -X 'main.Commit=${{ env.COMMIT }}' -X 'main.BuildTime=${{ env.BUILD_TIME }}'" -o dist/gobin-${{ matrix.goos }}-${{ matrix.goarch }}${{ env.file_name }} github.com/topisenpai/gobin/cli

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: gobin-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/*

      - name: Release
        if: ${{ github.event_name == 'release' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          allowUpdates: true
